export const ADD_STAFFS = 'ADD_STAFFS';
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';

export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const DEPARTMENT_FAILED = 'DEPARTMENT_FAILED';
export const DEPARTMENT_LOADING = 'DEPARTMENT_LOADING';

export const ADD_SALARY = 'ADD_SALARY';
export const SALARY_FAILED = 'SALARY_FAILED';
export const SALARY_LOADING = 'SALARY_LOADING';
export const ADD_STAFF_DEPART = 'ADD_STAFF_DEPART';
export const STAFFS_DEPART_LOADING = 'STAFFS_DEPART_LOADING';
export const STAFFS_DEPART_FAILED = 'STAFFS_DEPART_FAILED';

export const DELETE_STAFF = 'DELETE_STAFF';
